title : 125 Summer of Side Projects
name: '125 Summer of Side Projects'
description: '8 weeks of semi-guided side projects by CS 125 folks.'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Links
featured_posts:
  - url: '/ideas'
    title: 'Advice on Ideas'
  - url: '/workflow'
    title: 'Advice on Workflow'
  - url: 'https://cs125-forum.cs.illinois.edu/'
    title: 'Forum'

collections:
  news:
    title: Info
    default_open: false
    output: true
  posts:
    title: Workshops
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /:title
  - scope:
      type: news
    values:
      title: News
      permalink: /:title

plugins:
  - jekyll-sitemap
  - jekyll-toc
