# Site settings
title: "CS 125 Summer of Side Projects"
author: "CS 125 Staff"
description: "2 months of guided side projects to give people some experience with practical programming and building their portfolios during Summer 2021 online."
keywords: "Software Engineering, Side Projects, Web Bots, JavaScript, TypeScript, Python"
biography: "Just older students trying to help freshman"
colophon: "© 2021 — 2021<br>Theme and content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://netlify.com/'>Netlify</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "https://125summer.netlify.app/"

twitter_username: ferreira_hugo
github_username: hugoferreira
linkedin_username: hugoserenoferreira
facebook_username: hugo.sereno.ferreira
google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /:title/
